### ISSUE TITLE
Getting error with WebSocket connection

### ISSUE THREAD

**Issue by zeybek** [tobiasbeuving/vue-websocket-chat-client#1]
I am getting this error, can you help me ?

`WebSocket connection to 'ws://localhost:3001/?username=Tobias' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by zeybek** [comment]
Ok sorry I didn't see README

**Comment by rustigano** [comment]
> Ok sorry I didn't see README

No problem, let me know if you get it up and running or not.
Cheers

**Comment by zeybek** [comment]
> > Ok sorry I didn't see README
> 
> No problem, let me know if you get it up and running or not.
> Cheers

Working properly thanks !

**Comment by rustigano** [comment]
> > > Ok sorry I didn't see README
> > 
> > 
> > No problem, let me know if you get it up and running or not.
> > Cheers
> 
> Working properly thanks !

Thanks for letting me know!
